version: "3.8"
services:
  react-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
     - ./:/app
     - frontend-node:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start

volumes:
  frontend-node: