version: "3.8"
services:
  express-app:
    build:
      context: ./backend/
      args:
        NODE_ENV: development
    volumes:
     - ./backend:/app
     - backend-node:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  react-app:
    build:
      context: ./frontend/
      args:
        NODE_ENV: development
    volumes:
     - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: npm start 