version: "3.8"
services:
  express-app:
    build:
      context: ./backend/
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm start

  react-app:
    build:
      context: ./frontend/
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm start