version: "3.8"
services:
  express-app:
    build: ./backend/
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  react-app:
    build: ./frontend/
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

volumes:
  backend-node:
  frontend-node: