const testHealthforms = {
  TEST_HEALTHFORM1: {
    feverOrChills: false,
    suddenLossOfSenseOfSmellAndTaste: true,
    difficultyBreathingOrShortnessOfBreath: true,
    cough: true,
    runnyOrStuffyNose: true,
    outsideCanadaTravellingInPast14Days: true,
    closeContactWithSuspectedCase: true,
    unusualSevereFatigue: true,
    unusualHeadache: true,
    significantLossOfAppetite: true,
    unusualOrUnexplainedMusclePainOrStiffness: true,
    soreThroatWithoutObviousCause: true,
    hin: '456765',
    createdAt: '2022-04-05T07:14:57.536Z',
    updatedAt: '2022-04-05T07:14:57.536Z',
  },
  TEST_HEALTHFORM2: {
    feverOrChills: false,
    suddenLossOfSenseOfSmellAndTaste: false,
    difficultyBreathingOrShortnessOfBreath: false,
    cough: true,
    runnyOrStuffyNose: true,
    outsideCanadaTravellingInPast14Days: true,
    closeContactWithSuspectedCase: false,
    unusualSevereFatigue: false,
    unusualHeadache: false,
    significantLossOfAppetite: false,
    unusualOrUnexplainedMusclePainOrStiffness: false,
    soreThroatWithoutObviousCause: false,
    hin: '12322331',
    createdAt: '2022-04-05T04:31:16.524Z',
    updatedAt: '2022-04-05T04:31:16.524Z',
  },
  TEST_HEALTHFORM3: {
    feverOrChills: false,
    suddenLossOfSenseOfSmellAndTaste: false,
    difficultyBreathingOrShortnessOfBreath: false,
    cough: false,
    runnyOrStuffyNose: false,
    outsideCanadaTravellingInPast14Days: false,
    closeContactWithSuspectedCase: false,
    unusualSevereFatigue: true,
    unusualHeadache: true,
    significantLossOfAppetite: true,
    unusualOrUnexplainedMusclePainOrStiffness: true,
    soreThroatWithoutObviousCause: true,
    hin: '12312331',
    createdAt: '2022-04-05T07:15:29.691Z',
    updatedAt: '2022-04-05T07:15:29.691Z',
  },
  TEST_HEALTHFORM4: {
    feverOrChills: false,
    suddenLossOfSenseOfSmellAndTaste: false,
    difficultyBreathingOrShortnessOfBreath: false,
    cough: false,
    runnyOrStuffyNose: false,
    outsideCanadaTravellingInPast14Days: false,
    closeContactWithSuspectedCase: false,
    unusualSevereFatigue: true,
    unusualHeadache: true,
    significantLossOfAppetite: true,
    unusualOrUnexplainedMusclePainOrStiffness: true,
    soreThroatWithoutObviousCause: true,
    hin: '12312371',
    createdAt: '2021-04-05T07:15:29.691Z',
    updatedAt: '2021-04-05T07:15:29.691Z',
  },
};

module.exports = {
  testHealthforms,
};
