# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.0
jobs:
  backend-tests:
    docker:
      - image: 'cimg/node:17.4.0'
    steps:
      - checkout
      - run:
          name: "Install Node"
          command: npm install
          working_directory: ./
      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'MONGO_USER=$MONGO_USER' >> ./.env
            echo 'MONGO_PASS=$MONGO_PASS' >> ./.env
      - run:
          name: "Run linter"
          command: npm run lint .
          working_directory: ./
      - run:
          name: "Run tests"
          command: npm run test
          working_directory: ./
  frontend-tests:
    docker:
      - image: 'cimg/node:17.4.0'
    steps:
      - checkout
      - run:
          name: "Install Node"
          command: npm install
          working_directory: ./client
      - run:
          name: "Run linter"
          command: npm run lint .
          working_directory: ./client/
      - run:
          name: "Run tests"
          command: npm run test
          working_directory: ./client/

workflows:
  test_backend:
      jobs:
        - backend-tests
  test_frontend:
      jobs:
        - frontend-tests

